### ISSUE TITLE
Undefined name 'visuals' in ./util/util.py

### ISSUE THREAD

**Issue by cclauss** [richzhang/colorization-pytorch#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/richzhang/colorization-pytorch on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./util/util.py:70:18: F821 undefined name 'visuals'
        subset = visuals
                 ^
1     F821 undefined name 'visuals'
1
```

**Comment by richzhang** [comment]
Fixed, thanks
