### ISSUE TITLE
Discriminator in the pretrained model

### ISSUE THREAD

**Issue by kyleliang919** [richzhang/colorization-pytorch#4]
So I can see that there is a discriminator defined in the graph, if lambda_ GAN  > 0. Do you guys have pretrained models that use the discriminator? I am curious about the difference in performance with and without discriminator?
Or what are hyperparameters if providing a pretrained model is not possible?

**Comment by richzhang** [comment]
Hi, some of the discriminator code is inherited from the [pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix) code. I haven't tried training it with a discriminator. It may not be functional, but you are welcome to try to integrate it!

**Comment by K624-YCK** [comment]
hello mr.Zhang, you said you didn't train it with a discriminator, could you show me the training code without the discriminator? this repository only has the training code with the discriminator.
